spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
          filters:
            - name: Hystrix
              args:
               name: fallbackCommand
               fallbackuri: forward:/deptFallBack
          

server:
 port:
    8084

management.endpoints.web.exposure.include: "*"

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000