spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**

server:
 port:
    8084